apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : myapp3
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: app3
  source:
    path   : "HelmCharts/MyChart2"
    repoURL: "git@github.com:keneshbekov5k/keneshbekov.git"
    targetRevision: HEAD
    helm:
      valueFiles:
      - values_prod.yaml
      parameters:
      - name: "container.image"
        value: temson13/temson13

  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
